function [cargs, opts] = common_args(varargin)

  % Add absolute path to code
  if (exist('de_GetBaseDir')~=2)
    addpath(genpath(fullfile('..','..', 'code')));
    addpath(genpath(fullfile('..','..','..', 'code')));
    addpath(genpath(fullfile(de_GetBaseDir(),'code')));
    rmpath (genpath(fullfile('..','..','..', 'code')));
    rmpath (genpath(fullfile('..','..', 'code')));
  end;

  opts = {'small'};

  cargs = {  'parallel', true, 'debug', 1:10, 'ac.debug', 1:10, ...
             'distn',   {'norme'},  'mu',          0,    'sigma',     [ 4 8 ], ...
             'nHidden', 425*2     'hpl',           2,    'nConns',    10, ...
             ...% Input
             'ac.zscore', true, ...
             'ac.randState', 4, ...
             'ac.tol',       0/850, ... %tolerance for disconnected pixels
             ... % Training
             'ac.XferFn',   6,            'ac.useBias',  1, ...
             'ac.AvgError', 5E-4,         'ac.MaxIterations', 101, ...
             'ac.TrainMode','batch',      'ac.Pow', 1, ... %gradient power (usually 1)
             'ac.EtaInit',  3E-2,         'ac.Acc', 1.001, 'ac.Dec', 1.25, ... %tanh#2, bias=1 resilient
             'ac.lambda',   0.025, ... % regularization
             'ac.wmax',     inf, ...%1.00,...%1.00 ...
             'ac.WeightInitScale', 0.01, ...
             'ac.linout',   true, ...
             ... %rejections
             'ac.rej.props', {'err'},   ...
             'ac.rej.type',  {'max'},   ...
             'ac.rej.width', [nan],     ...
             ... %output
             'out.data', {'info','mat'}, ...
             'out.plots', {'png'}  ...
             ...
             varargin{:}
           };
%             'ac.TrainMode','resilient',  'ac.Pow', 1, ... %gradient power (usually 1)
%             'ac.EtaInit',  5E-3,         'ac.Acc', 5E-7, 'ac.Dec', 0.15, ... %tanh#2, bias=1 resilient