function [args,opts] = face_args(varargin)
%
%  Final shared settings for left-side-bias runs
  % Get shared args
  addpath('..');
  [cargs,opts] = common_args();
  rmpath('..');

  args = de_ArgsInit ( cargs{:}, ... %Network structure
            'runs',   25,          'ac.randState', 2,    'p.randState', 2, ...
             'p.XferFn', 4,               'p.useBias', 1, ...
                                          'p.nHidden', 50, ...
             'p.AvgError',  0,            'p.MaxIterations', 1500, ...
             'p.TrainMode','batch',       'p.Pow', 1, ... %gradient power (usually 1)
            'p.EtaInit',   3E-3,          'p.Acc', 1.001,  'p.Dec', 1.25, ... %tanh#2,bias=1
             'p.lambda',   0.0001,         ...% regularization
             'p.wmax', inf, ... %output
             'out.data', {'info','mat'}, ...
             'out.plots', {'png'},  ...
             'plots', {'ffts','images'}, ...
             'stats', {'ffts','images'}, ...
             varargin{:} );
