clear all variables; clear all globals;

[args,opts]  = face_args('plots', {}, 'stats', {}, ...
                            'runs',10, 'ac.zscore', 0.025, 'ac.EtaInit', 2E-1, 'ac.AvgError', 1E-4, 'ac.MaxIterations', 100,  ...
                            'errorType', 1, ...
                            'p.errorType', 3,... % cross-entropy
                            'p.XferFn', [6 3], ...  %sigmoid->sigmoid
                            'p.zscore', 0.15, ...
                            'p.EtaInit', 5.1E-2, ...
                            'p.TrainMode', 'resilient', 'p.Acc', 1E-7, 'p.Dec', 0.25, ...
                            'p.dropout', 0.0, ...
                            'p.nHidden', 25, ...
                            'p.wlim', 2.0*[-1 1], ...
                            'p.MaxIterations', 500, ...
                            'p.AvgError', 1E-4, 'p.rej.width', [NaN], 'p.rej.type', {'max'} ...
                         
                            );%'plots',{'hu-encodings', 'hu-output'}, 'stats',{'hu-encodings', 'hu-output'});

% Run sergent task by training on all images
[trn, tst] = de_SimulatorUber('uber/natimg', 'young_bion_1981/orig/recog', opts, args);

