function args = depp_2D_args(varargin)
%
%  Final shared settings for 2YP runs
  addpath(genpath('../../../code/'));

  args = de_ArgsInit ( ... %Network structure
         {   'runs',    68,         'ac.randState', 2,    'p.randState', 2, ...
             'distn',   {'norme'}, 'mu',            0,    'sigma',       [ 3.0 6.0 ], ...
             'nHidden', 90*4,       'hpl',          4,    'nConns',      8, ...
             ...% Input
             'ac.tol',    0/403, ... %tolerance for disconnected pixels
             ... % Training
             'ac.XferFn',   6,            'ac.useBias',  1, ...
             'ac.AvgError', 5E-3,        'ac.MaxIterations', 102, ...
             'ac.TrainMode','resilient',  'ac.Pow', 3, ... %gradient power (usually 1)
             'ac.EtaInit',  1E-5,         'ac.Acc', 1E-6, 'ac.Dec', 0.25, ... %tanh#2, bias=1 resilient
             'ac.lambda',   0.05,  ...% regularization
             ...
             'p.XferFn', 4,               'p.useBias', 1, ...
                                          'p.nHidden', 1, ...
             'p.AvgError',  0,            'p.MaxIterations', 500, ...
             'p.TrainMode','batch',       'p.Pow', 1, ...
             'p.EtaInit',   0.01,         'p.Acc',  1.0025,  'p.Dec'  1.25 ... %sig,bias=0
             'p.lambda', 0.02, ...
             ... %rejections
             'ac.rej.props', {'err'},   'p.rej.props', {'err'}, ...
             'ac.rej.type',  {'max'},   'p.rej.type',  {'sample_std-normd'}, ...
             'ac.rej.width', [nan],     'p.rej.width', [3] ...
             ... %output
             'out.data', {'info','mat'}, ...
             'out.plots', {'png'},  ...
             'plots', {'ls-bars', 'images', 'ffts', 'connectivity'}, ...
             'stats', {'ffts', 'images'}, ...
         }, varargin{:} ); 