function [args,opt] = face_args(varargin)
%
%  Final shared settings for left-side-bias runs
  % Get shared args
  addpath('..');
  [cargs,opt] = common_args();
  rmpath('..');

  args = de_ArgsInit ( cargs{:}, ... %Network structure
             'runs',    25, ...
             'p.debug', [],...
             ...%'ac.MaxIterations', 15, ...
             'p.randState', 2, ...
             'p.XferFn', 4,               'p.useBias', 1, ...
                                          'p.nHidden', 50   , ...
             'p.AvgError',  0,            'p.MaxIterations', 250, ...
             'p.TrainMode','resilient',   'p.Pow', 3, ... %gradient power (usually 1)
             'p.EtaInit',   3E-5,         'p.Acc', 1E-6,  'p.Dec', 0.25, ... %tanh#2,bias=1
             'p.lambda',   0.01,         ...% regularization
             'p.wmax',    inf, ...
             'p.WeightInitScale', 0.01, ...
             ... %output
             'out.data', {'info','mat'}, ...
             'out.plots', {'png'},  ...
             'stats', {'images', 'ffts', 'ipd'}, ...
             'plots', {'images', 'ffts'}, ...%'ffts','images'}, ...
             varargin{:} );
