function [cargs, opts] = classic_args(varargin)

  [cargs,opts] = common_args( ...
             'runs',    40, ...
             ...
             'ac.zscore', 0.05, ...
             'ac.tol',    0*34/25, ... %tolerance for disconnected pixels
             ... % Training
             'ac.AvgError', 5E-5,         'ac.MaxIterations', 60, ...
             'ac.TrainMode','resilient',      'ac.Pow', 1, ... %gradient power (usually 1)
             'ac.EtaInit',  2.23E-2,         'ac.Acc', 1E-7, 'ac.Dec', 0.25, ... %5E-7 tanh#2, bias=1 resilient
             ...
             'p.errorType', 2, ...
              ...
             varargin{:} ...
           );
