% Model run with targets and distracter sets swapped

args = dac_2D_args('nHidden', 729*5, 'nConns', 15, ...
                   'ac.AvgError', 0,  'ac.MaxIterations', 5, 'ac.errorType', 2, ...
                   'errorType', 2, ...
                   ...
                   'ac.EtaInit',  0.01,  'ac.Acc', 1.05, 'ac.Dec', 1.25 ...
                  );

[mSets, models, stats] = de_SimulatorAC(2, 'mnist', {'patchSize', '28x28'}, args{:});
