function outdir = de_getOutPath(model, dirType)
%
% 
%
  stem                          = de_getDataFile(model.data.dim, ...
                                                 model.data.stimSet, ...
                                                 model.data.taskType, ...
                                                 model.data.opt, ...
                                                 sprintf('h%d_c%d', model.nHidden, model.nConns), ...
                                                 'dir');

  switch (dirType)
    case {'data', 'stats'},              
      if (guru_findstr(stem, model.out.datapath)==-1)
        outdir = fullfile(model.out.datapath, stem);
      else
        outdir = model.out.datapath;
      end;
      
    case {'results', 'plot', 'summary', 'settings-map'}
      if (guru_findstr(stem, model.out.resultspath)==-1)
        outdir = fullfile(model.out.resultspath, stem);
      else
        outdir = model.out.resultspath;
      end;

    case {'acn','pn'}
      origString = '';
      origString = [ origString ...
                     sprintf('SG=%s', sprintf('%f-', model.sigma(:))), ...
                     sprintf('AE=%f', model.ac.AvgError), ...
                     sprintf('MI=%d', model.ac.MaxIterations), ...
                     sprintf('AC=%f', model.ac.Acc), ...
                     sprintf('DC=%f', model.ac.Dec), ...
                     sprintf('EI=%f', model.ac.EtaInit), ...
                     sprintf('XF=%d', model.ac.XferFn), ...
                     sprintf('WT=%s', model.ac.WeightInitType) ];
      %hash = mfe_md5(origString);
      hash = sprintf('%d', sum(origString.*[1:10:10*length(origString)]));
      outdir = fullfile(de_getOutPath(model, 'data'), hash); %saving under data directory
      
    case {'ac', 'p'}
      origString = '';
      origString = [ origString ...
                     sprintf('SG=%s', sprintf('%f-', model.sigma(:))), ...
                     sprintf('AE=%f', model.ac.AvgError), ...
                     sprintf('MI=%d', model.ac.MaxIterations), ...
                     sprintf('AC=%f', model.ac.Acc), ...
                     sprintf('DC=%f', model.ac.Dec), ...
                     sprintf('EI=%f', model.ac.EtaInit), ...
                     sprintf('ET=%d', model.ac.errorType), ...
                     sprintf('XF=%d', model.ac.XferFn), ...
                     sprintf('WT=%d', model.ac.WeightInitType) ];
      %hash = mfe_md5(origString);
      hash = sprintf('%d', sum(origString.*[1:10:10*length(origString)]));
      outdir = fullfile(de_getOutPath(model, 'data'), hash); %saving under data directory

    otherwise
      error('Unknown type: %s', dirType);
  end;

  if (guru_findstr(de_getBaseDir(), outdir)==-1)
    outdir = fullfile(de_getBaseDir(), outdir);
  end;