% Train the autoencoder
[args,c_freqs,k_freqs]  = uber_args( 'runs', 50, 'ac.randState', 1050, ...
                     'ac.tol', 0, ...
                     'ac.XferFn', 6, 'ac.useBias', 0, ...
                     'ac.AvgError', 5E-4, 'ac.MaxIterations', 250, ...
                     'ac.EtaInit',  5E-6,  'ac.Acc', 1E-7, 'ac.Dec', 0.15, ... %tanh#2, bias=1 resilient
                     'ac.TrainMode','resilient', 'ac.Pow', 3, ...
                     'ac.lambda', [0.02 0.02 0.015 0.01 0.005] ...
             );

[mSets, models, stats] = de_Simulator('uber', 'all', '', {'c_freqs', c_freqs, 'k_freqs', k_freqs}, args{:});


% Get the autoencoder directories
ac = [models(1,:).ac];
dirs = cell(size(ac));
for i=1:length(ac)
   dirs{i} = guru_fileparts(ac(i).fn, 'path');
end;
clear('ac');

args{end+1} = 'uberpath';
args{end+1} = dirs;


%%%%%%%%%%%%%%%%
% Run each task
%%%%%%%%%%%%%%%%%


% Christman
c_args  = { args{:}, 'runs', 50, ...
             'plots', {}, 'stats', {}, ...
             'p.XferFn', 4,               'p.useBias', 1, ...
                                          'p.nHidden', 5, ...
             'p.AvgError',  0,            'p.MaxIterations', 1000, ...
             'p.TrainMode','batch',       'p.Pow',  1, ...
             'p.EtaInit',   0.005,        'p.Acc',  1.01,  'p.Dec',  1.25, ... %sig,bias=0
             'p.lambda',   0.0 ...
           };
de_Simulator('christman_etal_1991', 'low_freq',  'recog', {'freqs', c_freqs}, c_args{:});
de_Simulator('christman_etal_1991', 'high_freq', 'recog', {'freqs', c_freqs}, c_args{:});

% Sergent
s_args = { args{:}, 'runs', 68, ...
		 'plots', {'ls_bars'}, 'stats', {}, ...
		 'p.XferFn', 4,               'p.useBias', 1, ...
									  'p.nHidden', 1, ...
		 'p.AvgError',  0,            'p.MaxIterations', 500, ...
		 'p.TrainMode','batch',       'p.Pow', 1, ...
		 'p.EtaInit',   0.01,         'p.Acc',  1.0025,  'p.Dec'  1.25 ... %sig,bias=0
         };
de_Simulator('sergent_1982', 'de', 'sergent', {}, s_args{:});
de_Simulator('sergent_1982', 'de', 'sergent', {'D1#T1'}, s_args{:});
de_Simulator('sergent_1982', 'de', 'sergent', {'D1#T2'}, s_args{:});
de_Simulator('sergent_1982', 'de', 'sergent', {'D2#T1'}, s_args{:}); %rezad
de_Simulator('sergent_1982', 'de', 'sergent', {'D2#T2'}, s_args{:});
de_Simulator('sergent_1982', 'de', 'sergent', {'swapped'}, s_args{:});


% Kitterle
kf_args  = { args{:}, 'runs', 50, ...
             'plots', {}, 'stats', {}, ...
             'p.XferFn', 6,               'p.useBias', 1, ...
                                          'p.nHidden', 5, ...
             'p.AvgError',  0,            'p.MaxIterations', 2000, ...
             'p.TrainMode','batch',       'p.Pow',  1, ...
             'p.EtaInit',   0.005,         'p.Acc',  1.005,  'p.Dec',  1.15, ... %sig,bias=0
             ...%'p.EtaInit',   1E-2,         'p.Acc',  0,  'p.Dec',  0.15, ... %sig,bias=0
             'p.lambda',   0.0 ...
           };
de_Simulator('kitterle_etal_1992', 'sf_mixed', 'recog_freq', {'freqs', k_freqs}, kf_args{:});


kt_args  = { args{:}, 'runs', 50, ...
             'plots', {}, 'stats', {}, ...
             'p.XferFn', 4,               'p.useBias', 1, ...
                                          'p.nHidden', 5, ...
             'p.AvgError',  0,            'p.MaxIterations', 500, ...
             'p.TrainMode','batch',       'p.Pow',  1, ...
             'p.EtaInit',   0.005,        'p.Acc',  1.001,  'p.Dec',  1.25, ... %sig,bias=0
             'p.lambda',   0.0 ...
           };
de_Simulator('kitterle_etal_1992', 'sf_mixed', 'recog_type', {'freqs', k_freqs}, kt_args{:});

