% Sergent stims, task, and target set, using cross-entropy error
clear all variables;

[args,opts] = sergent_args('errorType', 3, ...
                           'p.errorType', 3,... % cross-entropy
                           'p.XferFn', [4 3], ...%soft-max=>logistic
                           'p.EtaInit', 1, ...
                           'p.nHidden', 5, ...
                           'p.wmax', 2.0, ...
                           'p.MaxIterations', 250 ...
                           );
[mSets, models, stats] = de_Simulator('sergent_1982', 'de', 'sergent', {opts{:}}, args{:});
