function [args,opts] = sergent_args(varargin)
%
%  Final shared settings for 2YP runs
%   http://www.willamette.edu/~gorr/classes/cs449/classify.html

  % Get shared args
  addpath('..');
  [cargs,opts] = common_args();
  rmpath('..');

  args = de_ArgsInit ( cargs{:}, ... %Network structure
             'runs',    5, ...
             ...
             'errorType', 2, ...
             ...%'ac.ts', 2, ...
             'p.errorType', 2, ...
             ...
             'p.randState', 2, ...
             'p.XferFn', 4, 'p.useBias', 1, ...
                                          'p.nHidden', 5, ...
             'p.AvgError',  0,            'p.MaxIterations', 25, ...
             'p.TrainMode','batch',       'p.Pow', 1, ...
             'p.EtaInit',   5E-2,         'p.Acc',  1.005,  'p.Dec',  1.25, ... %tanh,bias=1
             'p.lambda',    0.01, ...
             'p.noise_input', 0.00, ...
             'p.wlim', [-inf inf], ...
             'p.WeightInitScale', 1, ...
             ... %output
             'p.rej.props', {'err'}, ...
             'p.rej.type',  {'sample_std-normd'}, ...
             'p.rej.width', [3], ...
             ...
             'plots', {'ls-bars'}, ...
             'stats', {}, ...
             varargin{:} );


