function [args,opts] = sergent_args(varargin)
%
%  Final shared settings for 2YP runs
%   http://www.willamette.edu/~gorr/classes/cs449/classify.html

  % Get shared args
  addpath('..');
  [cargs,opts] = common_args();
  rmpath('..');

  args = de_ArgsInit ( cargs{:}, ... %Network structure
             'runs',    25, ...
             ...
             'p.randState', 2, ...
             'p.useBias', 1, ...
                                          'p.nHidden', 1, ...
             'p.AvgError',  0,            'p.MaxIterations', 100, ...
             'p.TrainMode','batch',       'p.Pow', 1, ...
             'p.EtaInit',   1E-2,         'p.Acc',  1.005,  'p.Dec',  1.25, ... %tanh,bias=1
             'p.lambda', 1E-4, ...
              'p.wmax', inf, ...
              'p.WeightInitScale', 0.01, ...
             ... %output
             'p.rej.props', {'err'}, ...
             'p.rej.type',  {'sample_std-normd'}, ...
             'p.rej.width', [3], ...
             ...
             'plots', {'ls-bars', 'ffts', 'images', 'connectivity'}, ...
             'stats', {'ipd', 'ffts', 'images'}, ...
             varargin{:} );


