function [args,opts] = discovery_sergent_args(varargin)
% These args are for exploring the parameter space.

  % Get shared args
  addpath('..');
  [args,opts] = discovery_args( ... %Network structure
                  'errorType', 2, 'p.errorType', 3,... % cross-entropy
                  'p.ndupes', 1,...
                  'p.XferFn', [6 7], ...  %sigmoid->sigmoid
                  ...'p.zscore_across', 0.15,...15,....15, ...%15, ...
                  'p.EtaInit', 2.1E-3, ...
...                  'p.TrainMode', 'batch', 'p.Pow', 1, ...
                  'p.TrainMode', 'resilient', 'p.Pow', 1, ...
...                  'p.Acc', 1.001, 'p.Dec', 1.25, ...
                  'p.Acc', 5E-6, 'p.Dec', 0.25, ...
                  'p.nHidden', 100, ...
                  'p.dropout', 0.0, ...
                  'p.wlim', inf*[-1 1], ...
                  'p.MaxIterations', 100, ...
                  'p.lambda', 0.0, ...%025, ...
                  'p.AvgError', 0, 'p.rej.width', [3], 'p.rej.type', {'sample_std-normd'}, ...
                  varargin{:} ...
                 );
