function [args,opts] = uber_sergent_args(varargin)
%
%  Final shared settings for 2YP runs
%   http://www.willamette.edu/~gorr/classes/cs449/classify.html

  % Get shared args
  addpath('..');
  [args,opts] = uber_args( 'out.pub', true, ... %Network structure
                  'p.zscore', 0.10, ...
                  'p.EtaInit', 2.1E-4, ...
                  'p.TrainMode', 'resilient', 'p.Pow', 1, ...
                  'p.Acc', 5E-6, 'p.Dec', 0.025, ...
                  'p.nHidden', 50, ...
                  'p.dropout', 0.5, ...
                  'p.noise_input', 0.0, ...
                  'p.wlim', inf*[-1 1], ...
                  'p.MaxIterations', 1000, ...
                  'p.lambda', 0.01, ...%025, ...
                  'p.AvgError', 0, 'p.rej.width', [3], 'p.rej.type', {'sample_std-normd'}, ...
                  varargin{:} ...
                 );
