function [args,opts] = uber_sergent_args(varargin)
%
%  Final shared settings for 2YP runs
%   http://www.willamette.edu/~gorr/classes/cs449/classify.html

  % Get shared args
  addpath('..');
  [args,opts] = uber_args( ... %Network structure
                  'errorType', 3, 'p.errorType', 3,... % cross-entropy
                  'p.ndupes', 10,...
                  'p.XferFn', [6 3], ...  %sigmoid->sigmoid
                  'p.zscore', 0.1,...15,....15, ...%15, ...
...                  'p.EtaInit', 1.5E-1, ...
...                  'p.TrainMode', 'batch', 'p.Pow', 1, ...
                  ...'p.Acc', 1.0025, 'p.Dec', 1.25, ...
                  'p.avgact', 0.1, ...
                  'p.bn', 3.3E-1, 'p.bc', 3.3E-2, ...
                  'p.TrainMode', 'resilient-homeostatic', ...
                  'p.EtaInit', 2.1E-3, ...
                  'p.Pow', 1, ...
                  'p.Acc', 5E-6, 'p.Dec', 0.25, ...
                  'p.nHidden', 25, ...
                  'p.dropout', 0.0, ...
                  'p.noise_input', 0.10, ...0025, ...
                  'p.wlim', inf*[-1 1], ...
                  'p.MaxIterations', 100, ...
                  'p.lambda', 0.0, ...%025, ...
                  'p.AvgError', 0, ...
                  'p.rej.width', [5], 'p.rej.type', {'sample_std-normd'}, ...
                  varargin{:} ...
                 );
