function [args,opts] = uber_sergent_args(varargin)
%
%  Final shared settings for 2YP runs
%   http://www.willamette.edu/~gorr/classes/cs449/classify.html

  % Get shared args
  addpath('..');
  [args,opts] = uber_args( ... %Network structure
                  'errorType', 2, 'p.errorType', 2,... % cross-entropy
                  'p.XferFn', [6 6], ...  %sigmoid->sigmoid
                  'p.zscore', 0.15, ...
                  'p.EtaInit', 5E-2, ...
                  'p.TrainMode', 'batch', 'p.Pow', 1, ...
                  'p.Acc', 1.001, 'p.Dec', 1.25, ...
                  'p.nHidden', 6, ...
                  'p.wlim', inf*[-1 1], ...
                  'p.MaxIterations', 100, ...
                  'p.lambda', 0.001, ...
                  'p.AvgError', 0, 'p.rej.width', [2], 'p.rej.type', {'sample_std-normd'}, ...
                  varargin{:} ...
                 );
