function [args,sz] = sergent_args(varargin)
%
%  Final shared settings for 2YP runs

  % Get shared args
  addpath('..');
  [cargs,sz] = common_args();
  rmpath('..');
  
  args = de_ArgsInit ( cargs{:}, ... %Network structure
             'runs',    7, ...
             ....
             'p.randState', 2, ...
             'p.XferFn', 4,               'p.useBias', 1, ...
                                          'p.nHidden', 1, ...
             'p.AvgError',  0,            'p.MaxIterations', 50, ...
             'p.TrainMode','batch',       'p.Pow', 1, ...
             'p.EtaInit',   5E-3,         'p.Acc',  1.005,  'p.Dec',  1.25, ... %tanh,bias=1
             'p.lambda', 1E-4, ...
             'p.wmax', inf, ...
              ... %output
             'plots', {'ls-bars', 'ffts', 'images', 'connectivity'}, ...
             'stats', {'ipd', 'ffts', 'images'}, ...
             varargin{:} ); 

