clear all variables; clear all globals;

plts = {}%'ffts','images','connectivity','ls-bars'};
stats = {}%'ffts','images','connectivity'};
[args,opts]  = sergent_args('plots',plts,'stats',stats,'runs',5, 'ac.zscore', 0.025, 'ac.EtaInit', 5E-1, 'ac.AvgError', 5E-5, ...
                            'errorType', 3, ...
                            'p.errorType', 3,... % cross-entropy
                            'p.XferFn', [6 3], ...  %sigmoid->sigmoid
                            'p.zscore', 0.15, ...
                            'p.EtaInit', 5.1E-2, ...
                            'p.TrainMode', 'resilient', 'p.Acc', 1E-7, 'p.Dec', 0.25, ...
                            'p.dropout', 0.0, ...
                            'p.nHidden', 25, ...
                            'p.wmax', 2.0, ...
                            'p.MaxIterations', 50, ...
                            'p.AvgError', 1E-4, 'p.rej.width', [NaN], 'p.rej.type', {'max'} ...
                         );
% Run sergent task by training on all images
[trn, tst] = de_SimulatorUber('uber/natimg', 'sergent_1982/de/sergent',         opts, args);
