function [args,opts] = uber_sergent_args(varargin)
%
%  Final shared settings for 2YP runs
%   http://www.willamette.edu/~gorr/classes/cs449/classify.html

  % Get shared args
  addpath('..');
  [args,opts] = uber_args( ... %Network structure
                  'p.errorType', 3,... % cross-entropy
                  'p.XferFn', [6 3], ...  %sigmoid->sigmoid
                  'p.zscore', 0.15, ...
                  'p.EtaInit', 5E-2, ...
                  'p.TrainMode', 'resilient', 'p.Pow', 1, ...
                  'p.Acc', 1E-7, 'p.Dec', 0.25, ...
                  'p.dropout', 0.5, ...
                  'p.nHidden', 25, ...
                  'p.wlim', 2.0*[-1 1], ...
                  'p.MaxIterations', 100, ...
                  'p.AvgError', 0, 'p.rej.width', [3], 'p.rej.type', {'sample_std-normd'}, ...
                  varargin{:} ...
                 );
