function [args,opts] = christman_args(varargin)
%
%  Final shared settings for 2YP runs

  % Get shared args
  addpath('..');
  [cargs,opts] = common_args();
  rmpath('..');
  
  %freqs = [0.06 0.12 0.18 0.24 0.32]
  %freqs = 3*[0.03 0.06 0.12 0.24 0.48]
  
%   0.1261    0.1829    0.2652 @ 0.01 showed HSF adv, LSF inter  
% 0.0400    0.0600    0.0861 showed lsf adv, hsf inter

  % Christman paper:
  %   ntrials: 128 trials/condition * 8 subjects = 1024
  %   model:   1024 trials / 16 trials/model = 64 model instances

  opts = {'cycles', [1.5 3 6 12 24], opts{:}};
  
  args  = de_ArgsInit(cargs{:}, ... %network structure
              'runs', 25, ...
             ...
             'p.debug', [], ...
             'p.randState', 2, ...
             'p.XferFn', 4,               'p.useBias', 1, ...
                                          'p.nHidden', 1000, ...
             'p.AvgError',  0,            'p.MaxIterations', 1000, ...
             'p.TrainMode','batch',       'p.Pow',  1, ...
             'p.EtaInit',   1E-3,         'p.Acc',  1.005,  'p.Dec',  1.25, ... %sig,bias=0
             'p.lambda',   0.001, ...
             'p.wmax', inf, ...
             ... %output
             'plots', {'rf-dots', 'ffts','images'}, ...
             'stats', {'ffts','images'}, ...
             varargin{:} ); 
