function [args,opts] = uber_christman_args(varargin)
%
%  Final shared settings for left-side-bias runs
  % Get shared args
  addpath('..');
  [args,opts] = uber_args( ...
                  'runs',   25, ...
                  'errorType', 3, ...
                  'p.errorType', 3,... % cross-entropy
                  'p.XferFn', [6 3], ...  %sigmoid->sigmoid
                  'p.zscore', 0.25, ...
                  'p.EtaInit', 5E-3, ...
                  'p.TrainMode', 'resilient', ...
                  'p.Acc', 3E-7, 'p.Dec', 0.25, ...
                  'p.dropout', 0.0, ...
                  'p.nHidden', 100, ...
                  'p.wlim', inf*[-1 1], ...
                  'p.lambda',0.005,...
                  'p.MaxIterations', 5, ...
                  ...%'p.MaxError', 0.01, 'p.rejWidth', NaN, 'p.rejType', 'sample_std', ...
                  varargin{:} ...
                );

%  cycles = [5 12]; % are we sure about this?
%  opts = {opts{:}, 'cycles', cycles};

