function [cargs, opts] = common_args(varargin)

  % Add absolute path to code
  if (exist('de_GetBaseDir')~=2)
    addpath(genpath(fullfile('..','..', 'code')));
    addpath(genpath(fullfile('..','..','..', 'code')));
    addpath(genpath(fullfile(de_GetBaseDir(),'code')));
    rmpath (genpath(fullfile('..','..','..', 'code')));
    rmpath (genpath(fullfile('..','..', 'code')));
  end;

  opts = {'medium'}; %[68 50];

  cargs = {  'parallel', false, 'debug', 1:10, 'ac.debug', 1:10, 'p.debug', 1:10, ...
             ...
             'distn',   {'norme'},  'mu',          0,    'sigma',      [ 5 10 ], ...
             'nHidden', 3400*1,     'hpl',         1,    'nConns',     12, ...
             ...% Input
             'ac.randState', 4, ...
             'ac.tol',       0/3400, ... %tolerance for disconnected pixels
             ... % Training
             'ac.XferFn',   6,            'ac.useBias',  1, ...
             'ac.AvgError', 5E-4,        'ac.MaxIterations', 101, ...
             'ac.TrainMode','batch',     'ac.Pow', 1, ... %gradient power (usually 1)
             'ac.EtaInit',  2E-2,         'ac.Acc', 1.001, 'ac.Dec', 1.15, ... %tanh#2, bias=1 resilient
             'ac.lambda',   0.01, ...%[0.02 0.01],  ...% regularization
             'ac.wmax',     0.75, ...
             'ac.linout',   true, ...
             ... %rejections
             'ac.rej.props', {'err'},   'p.rej.props', {'err'}, ...
             'ac.rej.type',  {'max'},   'p.rej.type',  {'sample_std-normd'}, ...
             'ac.rej.width', [nan],     'p.rej.width', [3] ...
             ...
             'ac.noise_input', 0.0001, ...
             'p.noise_input', 0.0001, ...
             'p.wmax', inf, ...
             ... %output
             'out.data', {'info','mat'}, ...
             'out.plots', {'png'}  ...
             ...
             varargin{:}
           };
