clear all variables; clear all globals;

stats = {'connectivity', 'images','ffts'};
plts = {'ls-bars', stats{:}};
[args,opts]  = shared_sergent_args('plots',plts,'stats',stats,'runs',25, ...
                            'ac.zscore', 0.05, 'ac.EtaInit', 2.1E-1, 'ac.AvgError', 1E-4, 'ac.MaxIterations', 100,  ...
                            'errorType', 1, ...
                            'p.errorType', 3,... % cross-entropy
                            'p.XferFn', [6 3], ...  %sigmoid->sigmoid
                            'p.zscore', 0.15, ...
                            'p.EtaInit', 5E-2, ...
                            'p.TrainMode', 'resilient', 'p.Acc', 1E-7, 'p.Dec', 0.25, ...
                            'p.dropout', 0.0, ...
                            'p.nHidden', 10, ...
                            'p.wlim', 2.0*[-1 1], ...
                            'p.MaxIterations', 100, ...
                            'p.AvgError', 1E-5, 'p.rej.width', [NaN], 'p.rej.type', {'max'} ...
                            );
[args] = common_args_pruning(args{:}); %add pruning args at a lower priority

% Run sergent task by training on all images
[trn, tst] = de_SimulatorUber('uber/natimg', 'sergent_1982/de/sergent',         opts, args);
