function [args,opts] = face_args(varargin)
%
%  Final shared settings for left-side-bias runs
  % Get shared args
  addpath('..');
  [args,opts] = uber_args( ...
                  'runs',   25, ...
                  'p.zscore', 0.10, ...
                  'p.EtaInit', 5.4E-3, ...
                  'p.TrainMode', 'resilient', ...
                  'p.Acc', 1E-7, 'p.Dec', 0.025, ...
                  'p.dropout', 0.0, ...
                  'p.nHidden', 100, ...
                  'p.wlim', 0.5*[-1 1], ...
                  'p.lambda',0.025, ...
                  'p.noise_input', 0.005, ...
                  'p.MaxIterations', 200, ...
                  varargin{:} ...
                );
