function [args,opts] = face_args(varargin)
%
%  Final shared settings for left-side-bias runs
  % Get shared args
  addpath('..');
  [cargs,opts] = classic_args( ... 
             'runs',   25,                'ac.randState', 2,    'p.randState', 2, ...
             'p.XferFn', [6 2],           'p.useBias', 1, ...
                                          'p.nHidden', 25, ...
             'p.AvgError',  0,            'p.MaxIterations', 500, ...
             'p.TrainMode','resilient',       'p.Pow', 1, ... %gradient power (usually 1)
             'p.EtaInit',   3E-2,          'p.Acc', 1E-7,  'p.Dec', 0.25, ... %tanh#2,bias=1
             'p.lambda',   0.00,         ...% regularization
             'p.wlim', [-inf inf], ... %output
             ...
             'p.rej.props', {'err'}, ... %err,max,nan
             'p.rej.type',  {'sample_std-normd'}, ...
             'p.rej.width', [3], ...%3] ...
             ...
             'plots', {'ffts','images'}, ...
             'stats', {'ffts','images'}, ...
             varargin{:} );
