clear all variables; clear all globals;

[args,opts]  = face_args('plots', {'images','ffts'}, 'stats', {'images','ffts'}, 'runs', 5, ...
                            'ac.zscore', 0.05, 'ac.EtaInit', 1E-1, 'ac.Acc', 5E-6, 'ac.AvgError', 1E-4, 'ac.MaxIterations', 100,  ...
                            'errorType', 1, ...
                            'p.errorType', 3,... % cross-entropy
                            'p.XferFn', [6 7], ...  %sigmoid->sigmoid
                            'p.zscore', 0.25, ...
                            'p.EtaInit', 5.4E-2, ...
                            'p.TrainMode', 'resilient', 'p.Acc', 1E-7, 'p.Dec', 0.25, ...
                            'p.dropout', 0.5, ...
                            'p.nHidden', 30, ...
                            'p.wlim', 2.0*[-1 1], ...
                            'p.lambda',0.0,...
                            'p.MaxIterations', 250 ...
                            );%'plots',{'hu-encodings', 'hu-output'}, 'stats',{'hu-encodings', 'hu-output'});

% Run sergent task by training on all images
[trn, tst] = de_SimulatorUber('uber/natimg', 'young_bion_1981/orig/recog', opts, args);

