function [args,opts] = face_args(varargin)
%
%  Final shared settings for left-side-bias runs
  % Get shared args
  addpath('..');
  [args,opts] = uber_args( ...
                  'runs',   2, ...
                  'errorType', 3, ...
                  'p.errorType', 3,... % cross-entropy
                  'p.XferFn', [6 3], ...  %sigmoid->sigmoid
                  'p.zscore', 0.15, ...
                  'p.EtaInit', 1.0E-1, ...
                  'p.TrainMode', 'batch', 'p.Pow', 1, ...
                  'p.Acc', 1.001, 'p.Dec', 1.25, ...
                  ...'p.EtaInit', 5.4E-2, ...
                  ...'p.TrainMode', 'resilient', 'p.Pow', 1, ...
                  ...'p.Acc', 1E-7, 'p.Dec', 0.25, ...
                  ...'p.dropout', 0.0, ...
                  'p.nHidden', 25, ...
                  'p.wlim', inf*[-1 1], ...
                  'p.lambda',0.005,...
                  'p.noise_input', 0.01, ...
                  'p.MaxIterations', 100, ...
                  varargin{:} ...
                );
