function [cargs, opt] = common_args(varargin)

  % Add absolute path to code
  if (exist('de_GetBaseDir')~=2)
    addpath(genpath(fullfile('..','..', 'code')));
    addpath(genpath(fullfile('..','..','..', 'code')));
    addpath(genpath(fullfile(de_GetBaseDir(),'code')));
    rmpath (genpath(fullfile('..','..','..', 'code')));
    rmpath (genpath(fullfile('..','..', 'code')));
  end;

  c_dset = 'uber';
  opt    = {'small','dnw',true};% 'xdnw' c_dset};

  cargs = {  'parallel', false, 'debug', 1:10, 'ac.debug', 1:10 ...
             ... %
             'distn',   {'norm'},  'mu',          0,    'sigma',     [ 5.9 6.0 ], ...
             'nHidden', 213*4     'hpl',          4,    'nConns',    10, ...
             ... %
             'ac.ct.dataset',   c_dset, ...
                'ac.ct.steps',     {[8 8 8 8] [1 1 1 1]}, ...
                'ac.ct.npruning_loops', 4, ... %the rest of the loops in iters_per are training only,     {[6 5 4 3 1] [2 2 1 1 1]}, ...
                'ac.ct.iters_per',   {[10 10 10 10] [10 10 10 10]}, ...%'ac.ct.iters_per_step', [15 1], ...
                'ac.ct.ac.AvgError',  0, ...
                'ac.ct.ac.TrainMode', 'batch', ...
                'ac.ct.ac.Pow',       1, ...
                'ac.ct.ac.EtaInitInit', 0.025, ...%.4, ...
                'ac.ct.ac.Acc',       1.05, ...
                'ac.ct.ac.Dec',       2, ...
                'ac.ct.ac.XferFn',    6, ...
                'ac.ct.ac.lambda',    0.025, ...
                'ac.ct.ac.wmax',      inf ...
                'ac.ct.ac.WeightInitType', 'sprand', ...
                'ac.ct.ac.WeightInitScale', 0.01, ...
                'ac.ct.ac.prune_loc', 'output', ...
                'ac.ct.ac.prune_strategy', 'weighted_weights', ...
                'ac.ct.ac.nzc_ok', false, ... %non-zero connections ok
                'ac.ct.keep_weights', true, ...
                'ac.ct.ac.noise_input',0.0001, ...
             ...% Input
             'ac.zscore', true, ...
             'ac.randState', 4, ...
             'ac.tol',       0/850, ... %tolerance for disconnected pixels
             ... % Training
             'ac.XferFn',   6,            'ac.useBias',  1, ...
             'ac.AvgError', 1E-3,         'ac.MaxIterations', 60, ...
             'ac.TrainMode','batch',  'ac.Pow', 1,            ... %gradient power (usually 1)
             'ac.EtaInit',  1E-1,         'ac.Acc', 1.05, 'ac.Dec', 2, ... %tanh#2, bias=1 resilient
             'ac.lambda',   0.01, ...                                    % regularization
             'ac.wmax',     inf, ...%1.00 ...
             'ac.linout',   true, ...
             'ac.noise_input', 0.0001, ...
             'p.noise_input', 0.0001, ...
             ... %rejections
             'ac.rej.props', {'err'},   ...
             'ac.rej.type',  {'sample_std-normd'},   ...
             'ac.rej.width', [4],     ...
             ... %output
             'out.data', {'info','mat'}, ...
             'out.plots', {'png'}  ...
             ...
             varargin{:}
           };
%             'ac.TrainMode','resilient',  'ac.Pow', 1, ... %gradient power (usually 1)
%             'ac.EtaInit',  5E-3,         'ac.Acc', 5E-7, 'ac.Dec', 0.15, ... %tanh#2, bias=1 resilient
