% Model run with targets and distracter sets swapped

[args,freqs] = uber_args('runs', 40, ...
                         'p.XferFn', 4,               'p.useBias', 1, ...
                                                      'p.nHidden', 5, ...
                         'p.AvgError',  0,            'p.MaxIterations', 500, ...
                         'p.TrainMode','batch',       'p.Pow',  1, ...
                         'p.EtaInit',   0.005,        'p.Acc',  1.001,  'p.Dec',  1.25, ... %sig,bias=0
                         'p.lambda',   0.0 ...
                        );

[mSets, models, stats] = de_Simulator('kitterle_etal_1992', 'sf_mixed', 'recog_type', {'freqs', freqs}, args{:});
