function args = depp_2D_args(varargin)
%
%  Final shared settings for 2YP runs
  addpath(genpath('../../code/'));

  args = de_ArgsInit ( ... %Network structure
         {   'runs',    25,         'ac.randState', 2,    'p.randState', 2, ...
             'distn',   {'normre'}, 'mu',           0.5,  'sigma',       [ 0.5 1.5 2 2.5], ...
             'nHidden', 192*3,      'hpl',          3,    'nConns',      12, ...
             ...% Input
             'ac.tol',    0/403, ... %tolerance for disconnected pixels
             ... % Training
             'ac.XferFn',   6,            'ac.useBias',  1, ...
             'ac.AvgError', 5E-3,        'ac.MaxIterations', 50, ...
             'ac.TrainMode','resilient',  'ac.Pow', 3, ... %gradient power (usually 1)
             'ac.EtaInit',  1E-4,         'ac.Acc', 5E-7, 'ac.Dec', 0.25, ... %tanh#2, bias=1 resilient
             'ac.lambda',   0.01,         ...% regularization
             ...
             'p.XferFn', 4,               'p.useBias', 1, ...
                                          'p.nHidden', 1, ...
             'p.TrainMode', 'batch',      'p.Pow', 1, ...
             'p.AvgError',  0,            'p.MaxIterations', 100, ...
             'p.EtaInit',   0.01,         'p.Acc',  1.0025,  'p.Dec'  1.25 ... %sig,bias=0
             ... %rejections
             'ac.rej.props', {'err'},   'p.rej.props', {'err'}, ...
             'ac.rej.type',  {'max'},   'p.rej.type',  {'sample_std-normd'}, ...
             'ac.rej.width', [nan],     'p.rej.width', [3] ...
             ... %output
             'out.data', {'info','mat'}, ...
             'out.plots', {'png'},  ...
             'plots', {'ls-bars', 'images', 'ffts', 'connectivity'}, ...
             'stats', {'ffts','ipd'}, ...
         }, varargin{:} ); 
