% Train the autoencoder
n_ac = 10;
[args,c_freqs,k_freqs]  = uber_args( 'runs', n_ac, 'plots', {}, 'stats', {} );
[mSets, models, stats] = de_Simulator('uber', 'all', '', {'nInput', [34 25], 'c_freqs', c_freqs, 'k_freqs', k_freqs}, args{:});


% Get the autoencoder directories
ac = [models(1,:).ac];
dirs = cell(size(ac));
for i=1:length(ac)
   dirs{i} = guru_fileparts(ac(i).fn, 'path');
end;
clear('ac');

args{end+1} = 'uberpath';
args{end+1} = dirs;


%%%%%%%%%%%%%%%%
% Run each task
%%%%%%%%%%%%%%%%%


% Sergent
s_args = { args{:}, 'runs', min(n_ac, 68), ...
         'plots', {'ls_bars'}, 'stats', {}, ...
         'p.XferFn', 6,               'p.useBias', 1, ...
                                      'p.nHidden', 5, ...
         'p.AvgError',  0,            'p.MaxIterations', 100, ...
         'p.TrainMode','resilient',   'p.Pow', 1, ...
         'p.EtaInit',   1E-4,         'p.Acc',  3E-6,  'p.Dec'  0.25 ... %tanh,bias=1
          'p.lambda', 0, ...%    0.02, ...%1E-4, ...
         };
de_Simulator('sergent_1982', 'de', 'sergent', {'nInput', [34 25]}, s_args{:});
de_Simulator('sergent_1982', 'de', 'sergent', {'nInput', [34 25], 'D1#T1'}, s_args{:});
de_Simulator('sergent_1982', 'de', 'sergent', {'nInput', [34 25], 'D1#T2'}, s_args{:});
de_Simulator('sergent_1982', 'de', 'sergent', {'nInput', [34 25], 'D2#T1'}, s_args{:}); %rezad
de_Simulator('sergent_1982', 'de', 'sergent', {'nInput', [34 25], 'D2#T2'}, s_args{:});
de_Simulator('sergent_1982', 'de', 'sergent', {'nInput', [34 25], 'swapped'}, s_args{:});


% Kitterle
kf_args  = { args{:}, 'runs', min(n_ac, 50), ...
             'plots', {}, 'stats', {}, ...
             'p.XferFn', 6,               'p.useBias', 1, ...
                                          'p.nHidden', 10, ...
             'p.AvgError',  0,            'p.MaxIterations', 2000, ...
             'p.TrainMode','batch',       'p.Pow',  1, ...
             'p.EtaInit',   5E-3,         'p.Acc',  1.001,  'p.Dec',  1.25, ... %sig,bias=0
             'p.lambda',   1E-5 ...
           };
de_Simulator('kitterle_etal_1992', 'sf_mixed', 'recog_freq', {'nInput', [34 25], 'freqs', k_freqs}, kf_args{:});


kt_args  = { args{:}, 'runs', min(n_ac, 68), ...
             'plots', {}, 'stats', {}, ...
             'p.XferFn', 6,               'p.useBias', 1, ...
                                          'p.nHidden', 5, ...
             'p.AvgError',  0,            'p.MaxIterations', 2000, ...
             'p.TrainMode','batch',       'p.Pow',  1, ...
             'p.EtaInit',   5E-3,         'p.Acc',  1.001,  'p.Dec',  1.25, ... %sig,bias=0
             'p.lambda',   1E-5 ...
           };
de_Simulator('kitterle_etal_1992', 'sf_mixed', 'recog_type', {'nInput', [34 25], 'freqs', k_freqs}, kt_args{:});


% Christman
c_args  = { args{:}, 'runs', min(n_ac, 50), ...
             'plots', {}, 'stats', {}, ...
             'p.XferFn', 6,               'p.useBias', 1, ...
                                          'p.nHidden', 5, ...
             'p.AvgError',  0,            'p.MaxIterations', 2000, ...
             'p.TrainMode','batch',       'p.Pow',  1, ...
             'p.EtaInit',   1E-3,         'p.Acc',  1.001,  'p.Dec',  1.15, ... %sig,bias=0
             'p.lambda',   1E-4 ...
           };
de_Simulator('christman_etal_1991', 'low_freq',  'recog', {'nInput', [34 25], 'freqs', c_freqs}, c_args{:});
de_Simulator('christman_etal_1991', 'high_freq', 'recog', {'nInput', [34 25], 'freqs', c_freqs}, c_args{:});



% LSB
h_args = { args{:}, 'runs', min(n_ac, 50), ...
            'p.errorType', 2, ...
            'p.XferFn',    6,           'p.useBias', 1, ...
                                        'p.nHidden', 50, ...
            'p.TrainMode', 'resilient', 'p.Pow',     1, ...
            'p.AvgError',  0,       'p.MaxIterations', 1000, ...
            'p.EtaInit',   2E-5,    'p.Acc', 1E-7,  'p.Dec', 0.15 ... %tanh#2,bias=1
            'p.lambda',    0.001 ...
         };
fprintf('Making datasets...');
de_Simulator('hsiao_etal_2008', 'orig', 'recog', {'small'}, h_args{:});
