function [args,c_freqs,k_freqs] = uber_args(varargin)
%
%  Final shared settings for 2YP runs
  addpath(genpath('../../../code'));
  
c_freqs = [0.03 0.06 0.12 0.24 0.48];
%c_freqs = [0.06 0.12 0.18 0.24 0.32];
%c_freqs = [0.06 0.12 0.24 0.48 0.96];
%c_freqs = [0.06 0.08 0.25 0.45 0.50];
k_freqs = [0.10 0.20];
%k_freqs = [0.05 0.15];

  args  = de_ArgsInit({ ...
              'ac.randState', 600,  ...
              'distn', {'norme'}, ...%{'gamma'}, ... %{'gammae'}, ...
              'mu',    0, ...%[2.25  2], ...     %[1.5    1.75], ...
              'sigma', [ 3.0 11.0 ], ...
              'nHidden', 192*3, 'hpl', 3, 'nConns', 10, ...
              ...
              'ac.tol', 0, ...
              'ac.XferFn', 6, 'ac.useBias', 1, ...
              'ac.AvgError', 1E-4, 'ac.MaxIterations', 150, ...
              'ac.EtaInit',  4E-5,  'ac.Acc', 4E-7, 'ac.Dec', 0.15, ... %tanh#2, bias=1 resilient
              'ac.TrainMode','resilient', 'ac.Pow', 3, ...
              'ac.lambda', 5E-3, ...%[0.02 0.02 0.015 0.01 0.005] ...
                   ...
              'ac.rej.props', {'err'}, ...
              'ac.rej.type',  {'max'}, ...
              'ac.rej.width', [nan],   ...
              ...
              'out.data', {'info','mat'}, ...
              'out.plots', {'png'},  ...
              'plots', {'images','ffts','connectivity'}, ...
              'stats', {'ffts'}, ... 

         }, varargin{:} ); 
                            