% Explore landscape of iterations for 
%   model convergence

args = depp_2D_args('plots',   {'ls-bars'}, ...
                 'stats',   {'none'}, ...
                 'nHidden', [], ...
                 'nConns',  [], ...
                 'ac.AvgError', [], 'ac.MaxIterations', [], ...
                 'p.AvgError',  [], 'p.MaxIterations',  [] ...
                 );

allstats = loopmeHL(2, 'de', 'sergent', {}, ...
                    ...
                    { 'ac.MaxIterations', 'ac.AvgError' }, ...
                    { [ 10 25 50 100 200 ], [0 0 0 0 0] }, ...
                    { 'p.MaxIterations', 'p.AvgError' }, ...
                    { [100 250 500 1000 3000 6000], [0 0 0 0 0 0] }, ...
                    ...
                    args{:} ...
                   );
