% Explore landscape of error for 
%   model convergence

args = depp_2D_args('plots',   {'ls-bars'}, ...
                 'stats',   {'none'}, ...
                 'ac.AvgError', [], 'ac.MaxIterations', [], ...
                 'p.AvgError',  [], 'p.MaxIterations',  [] );
                 
args = { args{:}, 'plots', {'ls-bars'}, 'stats', {} };

allstats = loopmeHL(2, 'de', 'sergent', {}, ...
          ...
          { 'ac.AvgError', 'ac.MaxIterations' }, ...
          { [ 0.075 0.05 0.035 0.025 0.015 0.010], ...
            [    10   25    60   125   250   500] }, ...
          ...
          { 'p.MaxIterations', 'p.AvgError' }, ...
          {  [25 50 100 250 500 1000 3000 6000], [0 0 0 0 0 0 0 0] }, ...
          ...
          args{:} ...
        );