function args = depp_args(varargin)
%
%  Final shared settings for 2YP runs
  addpath('..');

  args = DEArgsInit ( ...
         {   'runs', 68, 'randState', 2, ...
             'sigma', [4 18], ...
             'nHidden', 26, 'nConns', 100, ...
             ...
             'out.plots', {'png'},  ...
             'out.data', {'info','csv','mat'}, ...
             'plots', {'ls-bars','ffts'}, 'stats', {'ffts'}, ...
             ...
             'ac.AvgError', 0.025,  'ac.MaxIterations', 250, 'ac.errorType', 2, ...
             'p.AvgError',  0,     'p.MaxIterations',  100, 'p.errorType',  2, ...
             'errorType', 2, ...
             ...
             'ac.EtaInit',  0.10,  'ac.Acc', 1.05, 'ac.Dec', 1.25, ...
             'p.EtaInit',   0.05,  'p.Acc',  1.01,  'p.Dec'  1.25 ...
         }, varargin{:} ); 
