% Loop over the # of hidden nodes and connections,
%   and match to performance

args = depp_2D_args('plots',   {'none'}, ...
                    'stats',   {'vs'}, ...
                    'nHidden', [], ...
                    'nConns',  [], ...
                    'ac.AvgError', [], ...
                    'ac.MaxIterations', [] ...
                   );
nHidden = [ 13     15    26    30   60 ];
nConns  = [ 25 75 100 150 200 ]; 

allstats = loopmeHL(2, 'de', 'sergent', {}, ...
                    ...
                    { 'nHidden', 'ac.AvgError', 'ac.MaxIterations'}, ...
                    { nHidden, ...
                      [ 0       0 0.05   0.05 0.03 ], ...
                      [ 250   250   350   350  350 ] ...
                    }, ...
                    { 'nConns' }, ...
                    { nConns }, ...
                    ...
                    args{:} ...
                  );
        
  % Step 1: produce performance diff figure
  fig = de_PlotHLPerfDiff(allstats, nHidden, nConns);
  print(fig.handle, '-dpng', ['depp_2D_loop_hidden_' fig.name]);

  % Step 2: produce human fit figure
  fig = de_PlotHLHumanFit(allstats, nHidden, nConns);
  print(fig.handle, '-dpng', ['depp_2D_loop_hidden_' fig.name] );


  % Step 3: calculate correlation between perf difference and human fit
  [rho,pval] = de_StatsHLPerfDiffVsHumanFit(allstats)
  
