function args = depp_args(varargin)
%
%  Final shared settings for 2YP runs
  addpath('..');

  args = DEArgsInit ( ...
         {   'runs', 68, 'randState', 1, ...
             'sigma', [1.8 12], ...
             'nHidden', 15, 'nConns', 5, ...
             ...
             'out.plots', {'png'},  ...
             'out.data', {'info','csv','mat'}, ...
             'plots', {'ls-bars'}, 'stats', {}, ...
             ...
             'ac.AvgError', 0.04,  'ac.MaxIterations', 1000, 'ac.errorType', 2, ...
             'p.AvgError',  0,     'p.MaxIterations',  250, 'p.errorType',  2, ...
             'errorType', 2, ...
             'rej.types', {'maxerr', 'sample_std-normd'}, 'rej.width', 3, ...
             ...
             'ac.EtaInit',  0.10,  'ac.Acc', 1.05, 'ac.Dec', 1.25, ...
             'p.EtaInit',   0.05,  'p.Acc',  1.01,  'p.Dec'  1.25 ...
         }, varargin{:} ); 
