function [args,sz] = face_args(varargin)
%
%  Final shared settings for left-side-bias runs

  % Get shared args
  addpath('..');
  [cargs,sz] = common_args();
  rmpath('..');

  args = de_ArgsInit ( cargs{:}, ... %Network structure
             'runs',    10,          'ac.randState', 2,    'p.randState', 2, ...
             ... % Training
             'p.XferFn', 4,               'p.useBias', 1, ...
                                          'p.nHidden', 25, ...
             'p.AvgError',  0,            'p.MaxIterations', 5000, ...
             'p.TrainMode','resilient',   'p.Pow', 1, ... %gradient power (usually 1)
             'p.EtaInit',   1E-2,          'p.Acc', 1E-7,  'p.Dec', 0.25, ... %tanh#2,bias=1
             'p.lambda',   0.0,         ...% regularization
             ... %rejections
             'ac.rej.props', {'err'},   'p.rej.props', {'err'}, ...
             'ac.rej.type',  {'max'},   'p.rej.type',  {'max'}, ...%sample_std-normd'}, ...
             'ac.rej.width', [nan],     'p.rej.width', [NaN], ...%3] ...
             ... %output
             'out.data', {'info','mat'}, ...
             'out.plots', {'png'},  ...
             'plots', {'ffts','images'}, ...
             'stats', {'ffts','images'}, ...
             varargin{:} ); 
