clear all variables; clear all globals;

plts = {'ls-bars'};
stats = {'images'};
[args,opts]  = face_args('plots',plts,'stats',stats,'runs',5, 'ac.zscore', 0.025, 'ac.EtaInit', 5E-1, 'ac.AvgError', 5E-5, ...
                            'errorType', 1, ...
                            'p.errorType', 3,... % cross-entropy
                            'p.XferFn', [6 2], ...  %sigmoid->softmax
                            'p.zscore', 0.15, ...
                            'p.EtaInit', 5.1E-2, ...
                            'p.TrainMode', 'resilient', 'p.Acc', 1E-7, 'p.Dec', 0.25, ...
                            'p.dropout', 0.0, ...
                            'p.nHidden', 25, ...
                            'p.wmax', 2.0, ...
                            'p.MaxIterations', 50, ...
                            'p.AvgError', 1E-4, 'p.rej.width', [NaN], 'p.rej.type', {'max'} ...
  );

% Run sergent task by training on all images
[trn, tst] = de_SimulatorUber('uber/natimg', 'sergent_1982/de/sergent',         opts, args);