function [args,freqs] = kitterle_args(varargin)
%
%  Final shared settings for 2YP runs
  addpath(genpath('../../code/'));

  freqs = [0.049 0.098]; % are we sure about this?

  args = de_ArgsInit ( ... %Network structure
         {   'runs',    25,         'ac.randState', 2,    'p.randState', 2, ...
             'distn',   {'normre'}, 'mu',           1,    'sigma',       [ 0.5 1.5 2 2.5], ...
             'nHidden', 192*3,      'hpl',          3,    'nConns',      12, ...
             ...% Input
             'ac.tol',    1/403, ... %tolerance for disconnected pixels
             ... % Training
             'ac.XferFn',   6,            'ac.useBias',  0, ...
             'ac.AvgError', 5E-4,         'ac.MaxIterations', 50, ...
             'ac.TrainMode','resilient',  'ac.Pow', 3, ... %gradient power (usually 1)
             'ac.EtaInit',  1E-4,         'ac.Acc', 5E-7, 'ac.Dec', 0.25, ... %tanh#2, bias=1 resilient
             'ac.lambda',   0.01,         ...% regularization
             ... %rejections
             'ac.rej.props', {'err'},   'p.rej.props', {'err'}, ...
             'ac.rej.type',  {'max'},   'p.rej.type',  {'sample_std-normd'}, ...
             'ac.rej.width', [nan],     'p.rej.width', [3] ...
             ... %output
             'out.data', {'info','mat'}, ...
             'out.plots', {'png'},  ...
             'plots', {}, ...
             'stats', {}, ...
         }, varargin{:} ); 
